### ISSUE TITLE
can't run the simulator

### ISSUE THREAD

**Issue by guqiuyuan** [CMU-SAFARI/MQSim#1]
I try to install the simulator and run it in my vamre virtual machine(the system in virtual machine is ubuntu 16.04lts).but when the simulator run at 10% progress,an error happened,it shows Segmentation fault (core dumped).and it crashed.so how can i fix this

**Comment by c-w-m** [comment]
I had a similar problem on an earlier pull (also on Ubuntu 16.04) but the current trunk version is working.  Try getting a fresh clone of the project to see if the problem persists.
