### ISSUE TITLE
problem about running the trace of Financial1

### ISSUE THREAD

**Issue by gdchenahu** [CMU-SAFARI/MQSim#14]
When I run the Trace of Financial1 with MQSim, I found that when the write request is passed to the list of Waiting_user_requests in the device and the data of the write request is retrieved from the host, the write request placed in the list of Waiting_user_requests is abnormally deleted. And every time we run MQSim, the write requests that are deleted abnormally are different. Do you know what caused this?

**Comment by arashta** [comment]
Can you please post links to your input files (both configuration and workloads)? We need them to replicate the error.

**Comment by gdchenahu** [comment]
> Can you please post links to your input files (both configuration and workloads)? We need them to replicate the error.

Financial1: http://traces.cs.umass.edu/index.php/Storage/Storage
And the input files are as follows：
[Input files.zip](https://github.com/CMU-SAFARI/MQSim/files/2731272/Input.files.zip)
Thanks.
