### ISSUE TITLE
run syntax

### ISSUE THREAD

**Issue by sac2019** [CMU-SAFARI/MQSim#26]
hi,
should we use two xml files: workload.xml and ssdconfig.xml for run?
when I type the following commands:
./MQSIM -i  ssdconfig.xml  -w workload.xml

this error  appears:
terminate called after throwing an instance of 'std::bad_alloc'
  what(): std::bad_alloc
aborted (core dumped)

thanks

**Comment by arashta** [comment]
Dear @sac2019 ,
Both xml input files are required for MQSim execution. 
Can you please send us your SSD configuration and workload definition files, so that we can investigate the issue?
Thanks,
Arash

**Comment by sac2019** [comment]
I use the default workload and ssd config file.

**Comment by sac2019** [comment]
I change the default workload file (decrease the number of channel and Die), the problem is solved.
it seems two default files (ssdconfig and workload) do not not match.
