### ISSUE TITLE
Floating point exception while running Financial benchmark 

### ISSUE THREAD

**Issue by Codeforfun29** [CMU-SAFARI/MQSim#27]
Hi, I am facing some issues while running the simulator. The simulator is encountering floating point exception while running the trace.

**Comment by arashta** [comment]
Dear @Codeforfun29 ,

Sorry for the late reply.
Do you still face problems running MQSim? If yes, please send us the SSD configuration and workload definition files, so that we can investigate the issue.

Thanks,
Arash
