### ISSUE TITLE
Why is the CMT larger and the higher the end to end delay?

### ISSUE THREAD

**Issue by Arcklly** [CMU-SAFARI/MQSim#28]
Hi, I am facing a problem that the larger the CMT are, the higher the end to end delay.  When running the wsrch-small trace,  I increase the CMT capacity (2M, 4M, 6M...), and the end to end delays are also increasing.  I think larger CMT will reduce delay. Can you give me some hints?

**Comment by arashta** [comment]
Dear @Arcklly ,

Thanks for reporting the issue.
Can you please post your SSD configuration and workload definition files, so that we can investigate the issue?

Thanks,
Arash

**Comment by nayoaixw** [comment]
I now also encountered this problem. After many experiments, I found that the larger the capacity of CMT, the smaller the end-to-end delay, which is contrary to my idea. My workload is wsrch-samll, and the configuration changes CMT_Capacity only on the basis of the source code. I am anxious now T_T.
