### ISSUE TITLE
build warnings: slowdown_min and slowdown_min_reverse to large for double type

### ISSUE THREAD

**Issue by c-w-m** [CMU-SAFARI/MQSim#3]
Build warnings:
src/ssd/TSU_FLIN.cpp:351:25: warning: integer constant is so large that it is unsigned
   double slowdown_min = 10000000000000000000, slowdown_max = 0;
                         ^~~~~~~~~~~~~~~~~~~~
src/ssd/TSU_FLIN.cpp:378:33: warning: integer constant is so large that it is unsigned
   double slowdown_min_reverse = 10000000000000000000, slowdown_max_reverse = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
suggestion:
replace line 351:
double slowdown_min = 10000000000000000000, slowdown_max = 0;
with:
unsigned long long int slowdown_min = 10000000000000000000ULL, slowdown_max = 0ULL;

replace line 378:
double slowdown_min_reverse = 10000000000000000000, slowdown_max_reverse = 0;
with:
unsigned long long int slowdown_min_reverse = 10000000000000000000ULL, slowdown_max_reverse = 0ULL;

**Comment by arashta** [comment]
Thanks for the feedback. The implementation of the FLIN scheduler is not finalized yet. So, we temporarily removed it.
