### ISSUE TITLE
Simulation Stops earlier TPCC: requests serviced are way lower than requests generated 

### ISSUE THREAD

**Issue by mishrap-ssi** [CMU-SAFARI/MQSim#30]
(total requests generated: 23666510 total requests serviced:21992). Is it the simulator limitation ? I have set the Percentage_to_Be_Executed to be 100, still it persists. What parameters to check if we want it to run all requests.

Also is there a way we can run applications directly on top of MQSim as the paper describes that it can be done via gem5, rather than a trace-driven simulation (please suggest if you have a version for it).

**Comment by mishrap-ssi** [comment]
(total requests generated: 23666510 total requests serviced:21992). Is it the simulator limitation ? I have set the Percentage_to_Be_Executed to be 100, still it persists. What parameters to check if we want it to run all requests. 

Also is there a way we can run applications directly on top of MQSim as the paper describes that it can be done, rather than a trace-driven simulation (please suggest if you have a version for it).

**Comment by arashta** [comment]
Dear @mishrap-ssi ,

Thanks for reporting the issue.
Can you please send us the SSD configuration and workload definition files, so that we can investigate the issue.

For the gem5 release, please refer to [this](https://github.com/CMU-SAFARI/MQSim/issues/16) thread.

Best Regards,
Arash
