### ISSUE TITLE
NVMe Queue Arbitration (Flow priority)

### ISSUE THREAD

**Issue by joyantamishu** [CMU-SAFARI/MQSim#37]
Hello,

In the workload.xml file there is a option named _Priority_Class_ that can be set for different flows. What I understand from the readme description, we can set the relative I/O priority of different flows by setting the corresponding _Priority_Class_ value in the range {{URGENT, HIGH, MEDIUM, LOW}, which is very similar to the NVMe queue specification. I tried two different flows with two different  _Priority_Class_ values, one with URGENT and another with LOW. And after the simulation, when I see the statistics, I see almost no difference in performance at all ( the delay, IOPS etc of these two flows are almost similar, which supposed not to be the case). I put rest of the required attributes (i.e. _Read_Percentage_, _Average_Request_Size_, _Average_No_of_Reqs_in_Queue_ etc) of the two flows identical.  

So, what I want to know, whether this _Priority_Class_  of each flows really has some impact or this is left for the future enhancement.

Thanks
Joyanta

**Comment by arashta** [comment]
Hi Joyanta,

You need to set the value of the Transaction_Scheduling_Policy parameter to PRIORITY_OUT_OF_ORDER. The base scheduler, i.e., OUT_OF_ORDER, ignores NVMe policies.

Best Regards,
Arash
