### ISSUE TITLE
does mqsim support process variation ? and if yes where?

### ISSUE THREAD

**Issue by HrithikSampson** [CMU-SAFARI/MQSim#41]
does MQSIM support process variation. If yes in which file is it prominent

**Comment by arashta** [comment]
Hi @HrithikSampson,
MQSim does not support process variation. But, depending on your simulation goals, you may be able to easily implement it. Can you please clarify what do you want to simulate? Do you want to reflect process variation in the bit error rate or in the flash read/write/erase times?

**Comment by HrithikSampson** [comment]
@arashta thank you for replying . I want to simulate a mixture of both but primarily flash write times

**Comment by HrithikSampson** [comment]
actually it would be also okay if i simulate only process variation in flash read / write / erase times

**Comment by arashta** [comment]
Hi @HrithikSampson,
I hope it is not too late for your answer. You can easily change the Get_command_execution_latency function in the Flashi_Chip.h file and implement any process variation scheme there based on pageID;

**Comment by HrithikSampson** [comment]
I had figured it out.  But thank you for the support.
