### ISSUE TITLE
Does MQSim support simulation of a storage cluster?

### ISSUE THREAD

**Issue by DanlinJia** [CMU-SAFARI/MQSim#44]
Hi,
I just wonder if MQSim supports simulation of a storage cluster? 
Could we launch multiple MQSim and expose the simulator to users as a storage cluster?

**Comment by arashta** [comment]
Hi @DanlinJia,

MQSim does not support simulation of a storage cluster. But, you can modify some of the host modules to implement storage cluster implementation. If you let us know your desired scenario, we can help you with that.

**Comment by DanlinJia** [comment]
Thanks for replying. We decide to isolate SSD simulations from SAN.
