### ISSUE TITLE
Get response time for each request?

### ISSUE THREAD

**Issue by DanlinJia** [CMU-SAFARI/MQSim#45]
Hi,

I'm defining a trace-based workload to feed MQSim.
I wonder is that possible to get the finish time of each request?
If yes, which file should I modify?

Thanks,
Danlin

**Comment by arashta** [comment]
Hi @DanlinJia,
Yes, it is possible to get the finish time for each request. Depending on your Host Interface type, which could be NVMe or SATA, you need to touch the SATA_consume_io_request function or NVMe_consume_io_request in IO_Flow_Base.cpp file, respectively.
