### ISSUE TITLE
in MQSim paper i had seen that fio generates the trace files but  device number and address column is not generated in fio where can i find such a tool to do it. And Device Number is not used much in the code can i keep it random uniform

### ISSUE THREAD

**Issue by HrithikSampson** [CMU-SAFARI/MQSim#51]

**Comment by tavakara** [comment]
Hi @HrithikSampson,
The device number is from the ASCII trace file standard! We are not using it in the simulations.
We used fio for real system benchmarking. For the simulations we used the synthetic workload generator in MQSIM that replicates the behvaior of a real synthetic device benchmarking tool.

**Comment by HrithikSampson** [comment]
Thank you sir for replying very quickly
