### ISSUE TITLE
missing parameters in README.md, XML parse error for Use_Copyback_GC

### ISSUE THREAD

**Issue by c-w-m** [CMU-SAFARI/MQSim#8]
[proposed changes diff](https://github.com/c-w-m/MQSim/commit/fb0896517c14c8f21d0135c84aa91da8348f72d9)
README.md
+17. **Ideal_Mapping_Table:** if mapping is ideal, table is enabled in which all address translations entries are always in CMT (i.e., CMT is infinite in size) and thus all adddress translation requests are always successful (i.e., all the mapping entries are found in the DRAM and there is no need to read mapping entries from flash)

and
+25. **Use_Copyback_for_GC:** used in GC_and_WL_Unit_Page_Level to determine block_manager→Is_page_valid gc_write transaction

exec/Device_parameter_Set.cpp
-	val = (Use_Copyback_for_GC ? "true" : "false");
+	val = (Ideal_Mapping_Table ? "true" : "false");

**Comment by arashta** [comment]
Thanks for your contribution.
